### ISSUE TITLE
Cabecera relación

### ISSUE THREAD

**Issue by AlmirHgo** [AlmirHgo/main-fan#2]
@marolivares cabecera de relación

**Comment by marolivares** [comment]
Una cabecera consiste en un conjunto de

**Comment by ghost** [comment]
Una cabecera en base de datos hace referencia al conjunto de atributos que tiene una entidad, y ya con base al manejo de tablas, una cabecera forma parte de la primera columna de la tabla.


![Image](https://github.com/AlmirHgo/main-fan/assets/157064691/d0892909-3e7e-44da-aff7-06fd468f62c8)
