### ISSUE TITLE
Cuerpo de la relacion

### ISSUE THREAD

**Issue by AlmirHgo** [AlmirHgo/main-fan#3]
Investigar cuerpo de la relacion @HERNANDEZHERNANDEZDANIEL

**Comment by HERNANDEZHERNANDEZDANIEL** [comment]
<section>
					<section>
						<h3>CUERPO DE LA RELACIÓN</h3>
						<p>Se refiere a las filas de una tabla que contienen los datos reales.
						También se conoce como el conjunto de tuplas o registros de la tabla.
						El cuerpo de la relación contiene la información específica que se almacena
						en la base de datos. Cada fila representa una entidad única o una instancia de
						la entidad que se está modelando. Cada columna del cuerpo de la relación corresponde
						a un atributo de esa entidad y contiene los valores de esos atributos para
						cada entidad individual.</p>
					</section>
					<section>
						<h3>EJEMPLO</h3>
						<p>Considera una tabla llamada "Clientes" con las siguientes filas en su cuerpo de relación:</p>
						<pre>
							<code>				
                               CLIENTES                         
		    +----+----------+----------+--------------------------+
		    | ID | Nombre   | Apellido | Correo electrónico       |
		    | 1  | Juan     | Pérez    | juan.perez@example.com   |
		    | 2  | María    | López    | maria.lopez@example.com  |
		    | 3  | Carlos   | García   | carlos.garcia@example.com|
			  +----+----------+----------+--------------------------+
							</code>
						</pre>
					</section>
					<section>
						<p>En este caso, cada fila representa un cliente diferente, y cada columna contiene
							información específica sobre ese cliente. El cuerpo de la relación es donde se almacenan
							los datos reales que se pueden consultar, modificar y manipular en la base de datos.</p>
					</section>
				</section>
