### ISSUE TITLE
Esquema de Relación

### ISSUE THREAD

**Issue by AlmirHgo** [AlmirHgo/main-fan#4]
Esquema de relación @LopezGarciaAxelSteven

**Comment by LopezGarciaAxelSteven** [comment]
<section>
					<section>
						<h3>EL ESQUEMA DE LA RELACIÓN</h3>
						<p>Es la estructura y el diseño de una tabla en particular.
							Contiene información sobre los atributos o columnas que componen la tabla,
							así como detalles sobre las restricciones y reglas que se aplican a esos atributos.</p>
					</section>
					<section>
						<h3>ELEMENTOS</h3>
						<p>1. Nombre de la tabla: Es el nombre que se le da a la tabla en la base de datos.</p>
					</section>
					<section>
						<h3>ELEMENTOS</h3>
						<p>2. Atributos o columnas: Son las características o campos que componen la tabla.
							Cada atributo tiene un nombre único y un tipo de dato asociado que especifica qué
							tipo de información puede almacenarse en él.</p>
					</section>
					<section>
						<h3>ELEMENTOS</h3>
						<p>3. Restricciones y reglas: Estas son las condiciones que se aplican a los datos en la tabla
							para garantizar la integridad y consistencia de la base de datos. Las restricciones pueden
							incluir restricciones de integridad referencial, restricciones de clave primaria, restricciones de
							clave externa, reglas de validación de datos, entre otras.</p>
					</section>
					<section>
						<h3>ELEMENTOS</h3>
						<p>4. Clave primaria: Es un atributo o conjunto de atributos que identifica de forma única cada fila en la tabla.
							No puede contener valores duplicados ni valores nulos.</p>
						<p>5. Índices: Son estructuras que se crean en la base de datos para mejorar el rendimiento de
							las consultas al acelerar la recuperación de datos.</p>
					</section>
					<section>
						<h3>EJEMPLO</h3>
						<p>Este esquema de relación describe la estructura de la tabla "Empleados",
							especificando los nombres de las columnas y el tipo de datos que contienen.
							Cada fila de la tabla representa un empleado con información específica sobre su identificación,
							nombre, apellido, departamento y salario.</p>
							<pre>
								<code>
											   Tabla: Empleados
	+------------------------------------------------------------------------+										   
	| ID_empleado  | Nombre      | Apellido     | Departamento     | Salario |
	| 1            | Juan        | Pérez        | Ventas           | 30000   |
	| 2            | María       | López        | Recursos Humanos | 35000   |
	| 3            | Carlos      | Martínez     | IT               | 40000   |
	+------------------------------------------------------------------------+
								</code>
							</pre>
					</section>
					<section>
						<p>En este ejemplo, la tabla "Empleados" tiene cinco columnas:
							- ID_empleado: identificador único para cada empleado (clave primaria)
							- Nombre: nombre del empleado
							- Apellido: apellido del empleado
							- Departamento: departamento al que pertenece el empleado
							- Salario: salario del empleado</p>
					</section>
				</section>

**Comment by LopezGarciaAxelSteven** [comment]
<section>
					<section>
						<h3>EL ESQUEMA DE LA RELACIÓN</h3>
						<p>Es la estructura y el diseño de una tabla en particular.
							Contiene información sobre los atributos o columnas que componen la tabla,
							así como detalles sobre las restricciones y reglas que se aplican a esos atributos.</p>
					</section>
					<section>
						<h3>ELEMENTOS</h3>
						<p>1. Nombre de la tabla: Es el nombre que se le da a la tabla en la base de datos.</p>
					</section>
					<section>
						<h3>ELEMENTOS</h3>
						<p>2. Atributos o columnas: Son las características o campos que componen la tabla.
							Cada atributo tiene un nombre único y un tipo de dato asociado que especifica qué
							tipo de información puede almacenarse en él.</p>
					</section>
					<section>
						<h3>ELEMENTOS</h3>
						<p>3. Restricciones y reglas: Estas son las condiciones que se aplican a los datos en la tabla
							para garantizar la integridad y consistencia de la base de datos. Las restricciones pueden
							incluir restricciones de integridad referencial, restricciones de clave primaria, restricciones de
							clave externa, reglas de validación de datos, entre otras.</p>
					</section>
					<section>
						<h3>ELEMENTOS</h3>
						<p>4. Clave primaria: Es un atributo o conjunto de atributos que identifica de forma única cada fila en la tabla.
							No puede contener valores duplicados ni valores nulos.</p>
						<p>5. Índices: Son estructuras que se crean en la base de datos para mejorar el rendimiento de
							las consultas al acelerar la recuperación de datos.</p>
					</section>
					<section>
						<h3>EJEMPLO</h3>
						<p>Este esquema de relación describe la estructura de la tabla "Empleados",
							especificando los nombres de las columnas y el tipo de datos que contienen.
							Cada fila de la tabla representa un empleado con información específica sobre su identificación,
							nombre, apellido, departamento y salario.</p>
							<pre>
								<code>
											   Tabla: Empleados
	+------------------------------------------------------------------------+										   
	| ID_empleado  | Nombre      | Apellido     | Departamento     | Salario |
	| 1            | Juan        | Pérez        | Ventas           | 30000   |
	| 2            | María       | López        | Recursos Humanos | 35000   |
	| 3            | Carlos      | Martínez     | IT               | 40000   |
	+------------------------------------------------------------------------+
								</code>
							</pre>
					</section>
					<section>
						<p>En este ejemplo, la tabla "Empleados" tiene cinco columnas:
							- ID_empleado: identificador único para cada empleado (clave primaria)
							- Nombre: nombre del empleado
							- Apellido: apellido del empleado
							- Departamento: departamento al que pertenece el empleado
							- Salario: salario del empleado</p>
					</section>
				</section>

**Comment by LopezGarciaAxelSteven** [comment]
<section>
					<section>
						<h3>EL ESQUEMA DE LA RELACIÓN</h3>
						<p>Es la estructura y el diseño de una tabla en particular.
							Contiene información sobre los atributos o columnas que componen la tabla,
							así como detalles sobre las restricciones y reglas que se aplican a esos atributos.</p>
					</section>
					<section>
						<h3>ELEMENTOS</h3>
						<p>1. Nombre de la tabla: Es el nombre que se le da a la tabla en la base de datos.</p>
					</section>
					<section>
						<p>2. Atributos o columnas: Son las características o campos que componen la tabla.
							Cada atributo tiene un nombre único y un tipo de dato asociado que especifica qué
							tipo de información puede almacenarse en él.</p>
					</section>
					<section>
						<p>3. Restricciones y reglas: Estas son las condiciones que se aplican a los datos en la tabla
							para garantizar la integridad y consistencia de la base de datos. Las restricciones pueden
							incluir restricciones de integridad referencial, restricciones de clave primaria, restricciones de
							clave externa, reglas de validación de datos, entre otras.</p>
					</section>
					<section>
						<p>4. Clave primaria: Es un atributo o conjunto de atributos que identifica de forma única cada
                                                        fila en la tabla. No puede contener valores duplicados ni valores nulos.</p>
						<p>5. Índices: Son estructuras que se crean en la base de datos para mejorar el rendimiento de
							las consultas al acelerar la recuperación de datos.</p>
					</section>
					<section>
						<h3>EJEMPLO</h3>
						<p>Este esquema de relación describe la estructura de la tabla "Empleados",
							especificando los nombres de las columnas y el tipo de datos que contienen.
							Cada fila de la tabla representa un empleado con información específica sobre su identificación,
							nombre, apellido, departamento y salario.</p>
							<pre>
								<code>
                                               Tabla: Empleados
	+-------------------------------------------------------------------------+										   
	| ID_empleado  | Nombre   | Apellido     | Departamento        | Salario |
	| 1                     | Juan         | Pérez          | Ventas                     | 30000  |
	| 2                     | María       | López         | Recursos Humanos | 35000  |
	| 3                     | Carlos      | Martínez     | IT                            | 40000  |
	+-------------------------------------------------------------------------+
								</code>
							</pre>
					</section>
					<section>
						<p>En este ejemplo, la tabla "Empleados" tiene cinco columnas:
							- ID_empleado: identificador único para cada empleado (clave primaria)
							- Nombre: nombre del empleado
							- Apellido: apellido del empleado
							- Departamento: departamento al que pertenece el empleado
							- Salario: salario del empleado</p>
					</section>
				</section>

**Comment by LopezGarciaAxelSteven** [comment]
<section>
					<section>
						<h3>EL ESQUEMA DE LA RELACIÓN</h3>
						<p>Es la estructura y el diseño de una tabla en particular.
							Contiene información sobre los atributos o columnas que componen la tabla,
							así como detalles sobre las restricciones y reglas que se aplican a esos atributos.</p>
					</section>
					<section>
						<h3>ELEMENTOS</h3>
						<p>1. Nombre de la tabla: Es el nombre que se le da a la tabla en la base de datos.</p>
					</section>
					<section>
						<p>2. Atributos o columnas: Son las características o campos que componen la tabla.
							Cada atributo tiene un nombre único y un tipo de dato asociado que especifica qué
							tipo de información puede almacenarse en él.</p>
					</section>
					<section>
						<p>3. Restricciones y reglas: Estas son las condiciones que se aplican a los datos en la tabla
							para garantizar la integridad y consistencia de la base de datos. Las restricciones pueden
							incluir restricciones de integridad referencial, restricciones de clave primaria, restricciones de
							clave externa, reglas de validación de datos, entre otras.</p>
					</section>
					<section>
						<p>4. Clave primaria: Es un atributo o conjunto de atributos que identifica de forma única cada fila
                                                        en la tabla. No puede contener valores duplicados ni valores nulos.</p>
						<p>5. Índices: Son estructuras que se crean en la base de datos para mejorar el rendimiento de
							las consultas al acelerar la recuperación de datos.</p>
					</section>
					<section>
						<h3>EJEMPLO</h3>
						<p>Este esquema de relación describe la estructura de la tabla "Empleados",
							especificando los nombres de las columnas y el tipo de datos que contienen.
							Cada fila de la tabla representa un empleado con información específica sobre su identificación,
							nombre, apellido, departamento y salario.</p>
							<pre>
								<code>
			        	   Tabla: Empleados
	+------------------------------------------------------------------------+										   
	| ID_empleado  | Nombre      | Apellido     | Departamento     | Salario |
	| 1            | Juan        | Pérez        | Ventas           | 30000   |
	| 2            | María       | López        | Recursos Humanos | 35000   |
	| 3            | Carlos      | Martínez     | IT               | 40000   |
	+------------------------------------------------------------------------+
								</code>
							</pre>
					</section>
					<section>
						<p>En este ejemplo, la tabla "Empleados" tiene cinco columnas:
							- ID_empleado: identificador único para cada empleado (clave primaria)
							- Nombre: nombre del empleado
							- Apellido: apellido del empleado
							- Departamento: departamento al que pertenece el empleado
							- Salario: salario del empleado</p>
					</section>
				</section>

**Comment by LopezGarciaAxelSteven** [comment]
<section>
					<section>
						<h3>EL ESQUEMA DE LA RELACIÓN</h3>
						<p>Es la estructura y el diseño de una tabla en particular.
							Contiene información sobre los atributos o columnas que componen la tabla,
							así como detalles sobre las restricciones y reglas que se aplican a esos atributos.</p>
					</section>
					<section>
						<h3>ELEMENTOS</h3>
						<p>1. Nombre de la tabla: Es el nombre que se le da a la tabla en la base de datos.</p>
					</section>
					<section>
						<p>2. Atributos o columnas: Son las características o campos que componen la tabla.
							Cada atributo tiene un nombre único y un tipo de dato asociado que especifica qué
							tipo de información puede almacenarse en él.</p>
					</section>
					<section>
						<p>3. Restricciones y reglas: Estas son las condiciones que se aplican a los datos en la tabla
							para garantizar la integridad y consistencia de la base de datos. Las restricciones pueden
							incluir restricciones de integridad referencial, restricciones de clave primaria, restricciones de
							clave externa, reglas de validación de datos, entre otras.</p>
					</section>
					<section>
						<p>4. Clave primaria: Es un atributo o conjunto de atributos que identifica de forma única
                                                        cada fila en la tabla. No puede contener valores duplicados ni valores nulos.</p>
						<p>5. Índices: Son estructuras que se crean en la base de datos para mejorar el rendimiento de
							las consultas al acelerar la recuperación de datos.</p>
					</section>
					<section>
						<h3>EJEMPLO</h3>
						<p>Este esquema de relación describe la estructura de la tabla "Empleados",
							especificando los nombres de las columnas y el tipo de datos que contienen.
							Cada fila de la tabla representa un empleado con información específica sobre su identificación,
							nombre, apellido, departamento y salario.</p>
							<pre>
								<code>
					        Tabla: Empleados
	+------------------------------------------------------------------------+										   
	| ID_empleado  | Nombre      | Apellido     | Departamento     | Salario |
	| 1            | Juan        | Pérez        | Ventas           | 30000   |
	| 2            | María       | López        | Recursos Humanos | 35000   |
	| 3            | Carlos      | Martínez     | IT               | 40000   |
	+------------------------------------------------------------------------+
								</code>
							</pre>
					</section>
					<section>
						<p>En este ejemplo, la tabla "Empleados" tiene cinco columnas:
							- ID_empleado: identificador único para cada empleado (clave primaria)
							- Nombre: nombre del empleado
							- Apellido: apellido del empleado
							- Departamento: departamento al que pertenece el empleado
							- Salario: salario del empleado</p>
					</section>
				</section>
